// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-77QuRK5xvxzbB_Glh7a21CZd_72lYM',
    appId: '1:881387238093:web:347d1edd6320920a13af84',
    messagingSenderId: '881387238093',
    projectId: 'hisseyatapp2026',
    authDomain: 'hisseyatapp2026.firebaseapp.com',
    storageBucket: 'hisseyatapp2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJJ2Vu--5kz3GAAQdkIWtlyA9T0A8924',
    appId: '1:881387238093:android:490986a0e787335d13af84',
    messagingSenderId: '881387238093',
    projectId: 'hisseyatapp2026',
    storageBucket: 'hisseyatapp2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qf0JT0_7WXmsB_bEAcfeYN_iPWFdM1U',
    appId: '1:881387238093:ios:a05da7c68f7fe52013af84',
    messagingSenderId: '881387238093',
    projectId: 'hisseyatapp2026',
    storageBucket: 'hisseyatapp2026.firebasestorage.app',
    iosBundleId: 'com.example.ilkDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qf0JT0_7WXmsB_bEAcfeYN_iPWFdM1U',
    appId: '1:881387238093:ios:a05da7c68f7fe52013af84',
    messagingSenderId: '881387238093',
    projectId: 'hisseyatapp2026',
    storageBucket: 'hisseyatapp2026.firebasestorage.app',
    iosBundleId: 'com.example.ilkDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk-77QuRK5xvxzbB_Glh7a21CZd_72lYM',
    appId: '1:881387238093:web:94a0980890084af913af84',
    messagingSenderId: '881387238093',
    projectId: 'hisseyatapp2026',
    authDomain: 'hisseyatapp2026.firebaseapp.com',
    storageBucket: 'hisseyatapp2026.firebasestorage.app',
  );
}
